-- =============================================================================
-- A-GW-N / Check CX
-- Supabase public schema bootstrap
-- 用途：可直接在 Supabase SQL Editor 执行的完整建库脚本
-- 特点：尽量幂等，避免重复执行时报 already exists
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- 1. 类型
-- -----------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'provider_type'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.provider_type AS ENUM ('openai', 'gemini', 'anthropic');
  END IF;
END;
$$;

-- -----------------------------------------------------------------------------
-- 2. 基础表
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.check_request_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  type public.provider_type NOT NULL,
  request_header jsonb,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.check_models (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type public.provider_type NOT NULL,
  model text NOT NULL,
  template_id uuid REFERENCES public.check_request_templates(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT check_models_type_model_key UNIQUE (type, model)
);

CREATE TABLE IF NOT EXISTS public.check_configs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type public.provider_type NOT NULL,
  model_id uuid NOT NULL REFERENCES public.check_models(id) ON DELETE RESTRICT,
  endpoint text NOT NULL,
  api_key text NOT NULL,
  enabled boolean DEFAULT true,
  is_maintenance boolean DEFAULT false,
  group_name text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.check_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id uuid NOT NULL REFERENCES public.check_configs(id) ON DELETE CASCADE,
  status text NOT NULL,
  latency_ms integer,
  ping_latency_ms double precision,
  checked_at timestamptz NOT NULL,
  message text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT check_status_valid CHECK (
    status IN ('operational', 'degraded', 'failed', 'validation_failed', 'error')
  ),
  CONSTRAINT check_latency_positive CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE TABLE IF NOT EXISTS public.group_info (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  group_name text NOT NULL UNIQUE,
  website_url text,
  tags text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.system_notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message text NOT NULL,
  is_active boolean DEFAULT true,
  level text DEFAULT 'info',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.homepage_blocks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  href text NOT NULL,
  description text NOT NULL DEFAULT '',
  status_label text NOT NULL DEFAULT 'Reserved',
  image_data_url text,
  col_span integer NOT NULL DEFAULT 1,
  row_span integer NOT NULL DEFAULT 1,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT homepage_blocks_col_span_check CHECK (col_span BETWEEN 1 AND 4),
  CONSTRAINT homepage_blocks_row_span_check CHECK (row_span BETWEEN 1 AND 3)
);

CREATE TABLE IF NOT EXISTS public.homepage_content (
  content_key text PRIMARY KEY,
  title text NOT NULL DEFAULT 'Information',
  hero_title text NOT NULL DEFAULT 'AI SERVICES',
  hero_subtitle text NOT NULL DEFAULT 'INTELLIGENCE MONITOR',
  entrance_badge text NOT NULL DEFAULT 'Welcome Sequence',
  entrance_brand text NOT NULL DEFAULT 'A-GW-N',
  entrance_title text NOT NULL DEFAULT '欢迎来到 A-GW-N 主页面',
  entrance_subtitle text NOT NULL DEFAULT '正在载入主页面矩阵与信息板，请稍候。',
  markdown text NOT NULL DEFAULT '',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

INSERT INTO public.homepage_content (content_key, title, markdown)
VALUES (
  'main_info',
  'Information',
  E'## A-GW-N\n\n这里可以放主页说明、使用入口提示、版本更新摘要，或者任何你希望展示在主页右侧的信息。'
)
ON CONFLICT (content_key) DO NOTHING;

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS image_data_url text;

ALTER TABLE public.homepage_content
  ADD COLUMN IF NOT EXISTS hero_title text NOT NULL DEFAULT 'AI SERVICES';

ALTER TABLE public.homepage_content
  ADD COLUMN IF NOT EXISTS hero_subtitle text NOT NULL DEFAULT 'INTELLIGENCE MONITOR';

ALTER TABLE public.homepage_content
  ADD COLUMN IF NOT EXISTS entrance_badge text NOT NULL DEFAULT 'Welcome Sequence';

ALTER TABLE public.homepage_content
  ADD COLUMN IF NOT EXISTS entrance_brand text NOT NULL DEFAULT 'A-GW-N';

ALTER TABLE public.homepage_content
  ADD COLUMN IF NOT EXISTS entrance_title text NOT NULL DEFAULT '欢迎来到 A-GW-N 主页面';

ALTER TABLE public.homepage_content
  ADD COLUMN IF NOT EXISTS entrance_subtitle text NOT NULL DEFAULT '正在载入主页面矩阵与信息板，请稍候。';

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS status_label text NOT NULL DEFAULT 'Reserved';

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS col_span integer NOT NULL DEFAULT 1;

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS row_span integer NOT NULL DEFAULT 1;

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

ALTER TABLE public.homepage_blocks
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS public.check_poller_leases (
  lease_key text PRIMARY KEY,
  leader_id text,
  lease_expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.gateway_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  provider_slug text NOT NULL,
  endpoint_url text NOT NULL,
  auth_mode text NOT NULL DEFAULT 'bearer',
  auth_token text,
  request_mode text NOT NULL DEFAULT 'openai',
  model_mappings jsonb NOT NULL DEFAULT '{}'::jsonb,
  brand_mappings jsonb NOT NULL DEFAULT '{}'::jsonb,
  default_headers jsonb NOT NULL DEFAULT '{}'::jsonb,
  extra_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  pool_table_pattern text,
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT gateway_profiles_auth_mode_check CHECK (auth_mode IN ('bearer', 'api_key', 'none')),
  CONSTRAINT gateway_profiles_request_mode_check CHECK (request_mode IN ('openai', 'messages'))
);

CREATE TABLE IF NOT EXISTS public.gateway_api_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key_name text NOT NULL UNIQUE,
  key_prefix text NOT NULL,
  secret_hash text NOT NULL UNIQUE,
  encrypted_key text,
  description text,
  key_scope text NOT NULL DEFAULT 'admin',
  owner_user_id uuid,
  is_enabled boolean NOT NULL DEFAULT true,
  last_used_at timestamptz,
  last_used_request_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT gateway_api_keys_key_scope_check CHECK (key_scope IN ('admin', 'user'))
);

CREATE TABLE IF NOT EXISTS public.gateway_request_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id text NOT NULL UNIQUE,
  profile_id uuid REFERENCES public.gateway_profiles(id) ON DELETE SET NULL,
  gateway_api_key_id uuid REFERENCES public.gateway_api_keys(id) ON DELETE SET NULL,
  gateway_api_key_name text,
  gateway_api_key_prefix text,
  user_id uuid,
  external_model text NOT NULL,
  mapped_model text NOT NULL DEFAULT '',
  brand text NOT NULL DEFAULT 'other',
  request_mode text NOT NULL DEFAULT 'openai',
  success boolean NOT NULL DEFAULT false,
  status_code integer,
  latency_ms integer,
  input_tokens integer DEFAULT 0,
  output_tokens integer DEFAULT 0,
  total_tokens integer DEFAULT 0,
  rpm_count integer DEFAULT 0,
  tpm_count integer DEFAULT 0,
  pool_table_name text,
  pool_record_id text,
  tool_count integer DEFAULT 0,
  image_count integer DEFAULT 0,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT gateway_request_logs_request_mode_check CHECK (request_mode IN ('openai', 'messages'))
);

CREATE TABLE IF NOT EXISTS public.auth_event_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL DEFAULT 'login',
  event_type text NOT NULL,
  success boolean NOT NULL DEFAULT false,
  auth_scope text NOT NULL DEFAULT 'user',
  actor_user_id uuid,
  actor_username text,
  actor_display_name text,
  actor_role text,
  provider text,
  target_path text,
  ip_address text,
  user_agent text,
  message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT auth_event_logs_category_check CHECK (category IN ('login', 'logout', 'access', 'error')),
  CONSTRAINT auth_event_logs_scope_check CHECK (auth_scope IN ('user', 'admin'))
);

CREATE TABLE IF NOT EXISTS public.statistics_overview (
  snapshot_key text PRIMARY KEY,
  total_usage bigint NOT NULL DEFAULT 0,
  rpm integer NOT NULL DEFAULT 0,
  tpm bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.statistics_request_trends (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bucket_at timestamptz NOT NULL UNIQUE,
  success_count integer NOT NULL DEFAULT 0,
  failed_count integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.statistics_brand_usage (
  brand text PRIMARY KEY,
  usage_count bigint NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT statistics_brand_usage_brand_check CHECK (brand IN ('gpt', 'gemini', 'claude', 'other'))
);

CREATE TABLE IF NOT EXISTS public.statistics_daily_usage (
  bucket_date date PRIMARY KEY,
  usage_total bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.statistics_hourly_usage (
  bucket_hour timestamptz PRIMARY KEY,
  usage_total bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.statistics_model_rankings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_name text NOT NULL,
  brand text NOT NULL DEFAULT 'other',
  usage_total bigint NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT statistics_model_rankings_brand_check CHECK (brand IN ('gpt', 'gemini', 'claude', 'other'))
);

CREATE TABLE IF NOT EXISTS public.statistics_account_pools (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pool_name text NOT NULL UNIQUE,
  total_accounts integer NOT NULL DEFAULT 0,
  active_accounts integer NOT NULL DEFAULT 0,
  status_label text NOT NULL DEFAULT 'Healthy',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.statistics_cards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  card_key text NOT NULL UNIQUE,
  title text NOT NULL,
  card_type text NOT NULL,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  is_enabled boolean NOT NULL DEFAULT true,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.account_pool_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pool_key text NOT NULL UNIQUE,
  table_name text NOT NULL UNIQUE,
  display_name text NOT NULL,
  brand text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text NOT NULL,
  auth_source text NOT NULL DEFAULT 'manual',
  oauth_provider text,
  oauth_subject text,
  oauth_username text,
  avatar_url text,
  profile_raw jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_login_at timestamptz,
  role text NOT NULL DEFAULT 'user',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT user_accounts_role_check CHECK (role IN ('user', 'admin')),
  CONSTRAINT user_accounts_auth_source_check CHECK (auth_source IN ('manual', 'linuxdo'))
);

CREATE TABLE IF NOT EXISTS public.user_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.user_accounts(id) ON DELETE CASCADE,
  session_token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_registration_settings (
  settings_key text PRIMARY KEY,
  registration_mode text NOT NULL DEFAULT 'closed',
  invite_code_hint text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT user_registration_settings_mode_check CHECK (registration_mode IN ('closed', 'open', 'invite_only'))
);

CREATE TABLE IF NOT EXISTS public.user_invite_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  note text,
  is_enabled boolean NOT NULL DEFAULT true,
  expires_at timestamptz,
  used_by_user_id uuid REFERENCES public.user_accounts(id) ON DELETE SET NULL,
  used_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.gateway_api_keys
  ADD COLUMN IF NOT EXISTS encrypted_key text;

ALTER TABLE public.gateway_api_keys
  ADD COLUMN IF NOT EXISTS key_scope text NOT NULL DEFAULT 'admin';

ALTER TABLE public.gateway_api_keys
  ADD COLUMN IF NOT EXISTS owner_user_id uuid;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'gateway_api_keys_key_scope_check'
  ) THEN
    ALTER TABLE public.gateway_api_keys
      ADD CONSTRAINT gateway_api_keys_key_scope_check CHECK (key_scope IN ('admin', 'user'));
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'gateway_api_keys_owner_user_id_fkey'
  ) THEN
    ALTER TABLE public.gateway_api_keys
      ADD CONSTRAINT gateway_api_keys_owner_user_id_fkey
      FOREIGN KEY (owner_user_id) REFERENCES public.user_accounts(id) ON DELETE SET NULL;
  END IF;
END;
$$;

ALTER TABLE public.user_accounts
  ADD COLUMN IF NOT EXISTS auth_source text NOT NULL DEFAULT 'manual';

ALTER TABLE public.user_accounts
  ADD COLUMN IF NOT EXISTS oauth_provider text;

ALTER TABLE public.user_accounts
  ADD COLUMN IF NOT EXISTS oauth_subject text;

ALTER TABLE public.user_accounts
  ADD COLUMN IF NOT EXISTS oauth_username text;

ALTER TABLE public.user_accounts
  ADD COLUMN IF NOT EXISTS avatar_url text;

ALTER TABLE public.user_accounts
  ADD COLUMN IF NOT EXISTS profile_raw jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.user_accounts
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'user_accounts_auth_source_check'
  ) THEN
    ALTER TABLE public.user_accounts
      ADD CONSTRAINT user_accounts_auth_source_check CHECK (auth_source IN ('manual', 'linuxdo'));
  END IF;
END;
$$;

-- -----------------------------------------------------------------------------
-- 3. 注释
-- -----------------------------------------------------------------------------

COMMENT ON TABLE public.check_request_templates IS '请求模板表，提供可复用的请求头和 metadata 默认值';
COMMENT ON TABLE public.check_models IS '模型配置表，存储可复用的模型定义与模板绑定';
COMMENT ON TABLE public.check_configs IS 'AI 服务商配置表';
COMMENT ON TABLE public.check_history IS '健康检测历史记录表';
COMMENT ON TABLE public.group_info IS '分组信息表';
COMMENT ON TABLE public.system_notifications IS '系统通知表';
COMMENT ON TABLE public.homepage_blocks IS '主页方块配置表，用于管理首页导航卡片';
COMMENT ON TABLE public.homepage_content IS '主页右侧信息板内容表，支持 Markdown';
COMMENT ON TABLE public.check_poller_leases IS '轮询主节点租约表（单行租约）';
COMMENT ON TABLE public.gateway_profiles IS 'Go 中转服务主配置表，管理员通过该表维护上游 provider、模型映射和消息模式';
COMMENT ON TABLE public.gateway_api_keys IS '网关访问密钥表，仅存储 sk 的哈希、前缀和后台描述信息';
COMMENT ON TABLE public.gateway_request_logs IS '中转请求日志表，记录模型调用、品牌、token 使用、状态和账号池信息';
COMMENT ON TABLE public.auth_event_logs IS '认证事件日志表，记录登录、退出、权限拒绝、邀请码流程等事件';
COMMENT ON TABLE public.statistics_overview IS '统计总览表，存储总用量、RPM、TPM 等摘要指标';
COMMENT ON TABLE public.statistics_request_trends IS '24 小时请求趋势表，存储每小时成功和失败请求计数';
COMMENT ON TABLE public.statistics_brand_usage IS '模型品牌分布表，存储 gpt / gemini / claude / other 的请求量';
COMMENT ON TABLE public.statistics_daily_usage IS '7 天每日用量统计表';
COMMENT ON TABLE public.statistics_hourly_usage IS '小时用量统计表';
COMMENT ON TABLE public.statistics_model_rankings IS '模型用量排行榜表';
COMMENT ON TABLE public.statistics_account_pools IS '账号池显示表，用于展示账号池总量与活跃量';
COMMENT ON TABLE public.statistics_cards IS '统计页卡片定义表，用于管理员维护统计面板结构';
COMMENT ON TABLE public.account_pool_registry IS '账号池注册表，记录可扫描的 {name}-pool 数据表';
COMMENT ON TABLE public.user_accounts IS '站内用户账号表';
COMMENT ON TABLE public.user_sessions IS '站内用户会话表';
COMMENT ON TABLE public.user_registration_settings IS '用户注册设置表，控制开放注册、关闭注册和邀请码注册';
COMMENT ON TABLE public.user_invite_codes IS '用户邀请码表，用于 Linux.do OAuth 注册准入';

COMMENT ON COLUMN public.check_request_templates.id IS '模板 UUID';
COMMENT ON COLUMN public.check_request_templates.name IS '模板名称（唯一）';
COMMENT ON COLUMN public.check_request_templates.type IS '模板提供商类型';
COMMENT ON COLUMN public.check_request_templates.request_header IS '模板默认请求头 (JSONB)';
COMMENT ON COLUMN public.check_request_templates.metadata IS '模板默认 metadata，请求体参数 (JSONB)';

COMMENT ON COLUMN public.check_models.id IS '模型 UUID';
COMMENT ON COLUMN public.check_models.type IS '模型提供商类型';
COMMENT ON COLUMN public.check_models.model IS '模型名称';
COMMENT ON COLUMN public.check_models.template_id IS '请求模板 ID';

COMMENT ON COLUMN public.check_configs.id IS '配置 UUID';
COMMENT ON COLUMN public.check_configs.name IS '配置显示名称';
COMMENT ON COLUMN public.check_configs.type IS '提供商类型';
COMMENT ON COLUMN public.check_configs.model_id IS '模型 ID';
COMMENT ON COLUMN public.check_configs.endpoint IS 'API 端点 URL';
COMMENT ON COLUMN public.check_configs.api_key IS 'API 密钥';
COMMENT ON COLUMN public.check_configs.enabled IS '是否启用检测';
COMMENT ON COLUMN public.check_configs.is_maintenance IS '维护模式';
COMMENT ON COLUMN public.check_configs.group_name IS '分组名称';

COMMENT ON COLUMN public.check_history.config_id IS '关联的配置 ID';
COMMENT ON COLUMN public.check_history.status IS '状态';
COMMENT ON COLUMN public.check_history.latency_ms IS '响应延迟 (毫秒)';
COMMENT ON COLUMN public.check_history.ping_latency_ms IS 'Ping 延迟 (毫秒)';
COMMENT ON COLUMN public.check_history.checked_at IS '检测时间';
COMMENT ON COLUMN public.check_history.message IS '状态消息或错误信息';

COMMENT ON COLUMN public.group_info.group_name IS '分组名称，关联 check_configs.group_name';
COMMENT ON COLUMN public.group_info.website_url IS '网站地址';
COMMENT ON COLUMN public.group_info.tags IS '分组 Tag 列表，英文逗号分隔字符串';

COMMENT ON COLUMN public.system_notifications.message IS '通知内容，支持 Markdown';
COMMENT ON COLUMN public.system_notifications.is_active IS '是否激活';
COMMENT ON COLUMN public.system_notifications.level IS '通知级别：info, warning, error';

COMMENT ON COLUMN public.homepage_blocks.slug IS '稳定唯一标识，用于程序识别与 upsert';
COMMENT ON COLUMN public.homepage_blocks.title IS '主页方块标题';
COMMENT ON COLUMN public.homepage_blocks.href IS '主页方块跳转路由';
COMMENT ON COLUMN public.homepage_blocks.description IS '主页方块描述';
COMMENT ON COLUMN public.homepage_blocks.status_label IS '方块状态标签，如 Live / Control / Reserved';
COMMENT ON COLUMN public.homepage_blocks.image_data_url IS '主页方块缓存图片，使用 data URL 文本保存';
COMMENT ON COLUMN public.homepage_blocks.col_span IS '桌面布局列跨度';
COMMENT ON COLUMN public.homepage_blocks.row_span IS '桌面布局行跨度';
COMMENT ON COLUMN public.homepage_blocks.sort_order IS '排序值，越小越靠前';
COMMENT ON COLUMN public.homepage_blocks.is_active IS '是否显示在主页';
COMMENT ON COLUMN public.homepage_content.content_key IS '信息板唯一键，默认 main_info';
COMMENT ON COLUMN public.homepage_content.title IS '信息板标题';
COMMENT ON COLUMN public.homepage_content.hero_title IS '首页欢迎主标题';
COMMENT ON COLUMN public.homepage_content.hero_subtitle IS '首页欢迎副标题';
COMMENT ON COLUMN public.homepage_content.entrance_badge IS '首页首次进入加载欢迎页徽标文本';
COMMENT ON COLUMN public.homepage_content.entrance_brand IS '首页首次进入加载欢迎页品牌文本';
COMMENT ON COLUMN public.homepage_content.entrance_title IS '首页首次进入加载欢迎页主标题';
COMMENT ON COLUMN public.homepage_content.entrance_subtitle IS '首页首次进入加载欢迎页副标题';
COMMENT ON COLUMN public.homepage_content.markdown IS '信息板 Markdown 正文';
COMMENT ON COLUMN public.gateway_profiles.profile_key IS '稳定唯一键，用于代码引用和 Go 服务加载';
COMMENT ON COLUMN public.gateway_profiles.provider_slug IS '上游 provider 标识';
COMMENT ON COLUMN public.gateway_profiles.endpoint_url IS '上游 API 地址';
COMMENT ON COLUMN public.gateway_profiles.auth_mode IS '认证方式';
COMMENT ON COLUMN public.gateway_profiles.auth_token IS '认证令牌或密钥';
COMMENT ON COLUMN public.gateway_profiles.request_mode IS '请求再次调用模式，openai 或 messages';
COMMENT ON COLUMN public.gateway_profiles.model_mappings IS '外部模型到内部模型的映射 JSON';
COMMENT ON COLUMN public.gateway_profiles.brand_mappings IS '模型到品牌的映射 JSON';
COMMENT ON COLUMN public.gateway_profiles.default_headers IS '额外请求头 JSON';
COMMENT ON COLUMN public.gateway_profiles.extra_payload IS '额外请求参数 JSON';
COMMENT ON COLUMN public.gateway_profiles.pool_table_pattern IS '账号池扫描模式，例如 %-pool';
COMMENT ON COLUMN public.gateway_api_keys.key_name IS '后台可读的密钥名称';
COMMENT ON COLUMN public.gateway_api_keys.key_prefix IS '用于界面识别的 sk 前缀摘要';
COMMENT ON COLUMN public.gateway_api_keys.secret_hash IS 'sk 的 SHA-256 哈希值';
COMMENT ON COLUMN public.gateway_api_keys.encrypted_key IS '使用服务端密钥加密存储的原始 sk，用于后台展示与用户重置';
COMMENT ON COLUMN public.gateway_api_keys.key_scope IS '密钥作用域：admin 或 user';
COMMENT ON COLUMN public.gateway_api_keys.owner_user_id IS '当 key_scope=user 时绑定的用户 ID';
COMMENT ON COLUMN public.gateway_api_keys.last_used_at IS '最近一次成功匹配该密钥的时间';
COMMENT ON COLUMN public.gateway_api_keys.last_used_request_id IS '最近一次使用时对应的请求 ID';
COMMENT ON COLUMN public.gateway_request_logs.gateway_api_key_id IS '本次请求命中的网关访问密钥 ID';
COMMENT ON COLUMN public.gateway_request_logs.gateway_api_key_name IS '写日志时缓存的密钥名称';
COMMENT ON COLUMN public.gateway_request_logs.gateway_api_key_prefix IS '写日志时缓存的密钥前缀';
COMMENT ON COLUMN public.gateway_request_logs.external_model IS '客户端请求的原始模型名';
COMMENT ON COLUMN public.gateway_request_logs.mapped_model IS '映射后的目标模型名';
COMMENT ON COLUMN public.gateway_request_logs.brand IS '模型品牌';
COMMENT ON COLUMN public.gateway_request_logs.success IS '请求是否成功';
COMMENT ON COLUMN public.gateway_request_logs.rpm_count IS '本次请求对应的 RPM 统计值';
COMMENT ON COLUMN public.gateway_request_logs.tpm_count IS '本次请求对应的 TPM 统计值';
COMMENT ON COLUMN public.gateway_request_logs.pool_table_name IS '命中的账号池表名';
COMMENT ON COLUMN public.gateway_request_logs.pool_record_id IS '命中的账号池记录主键';
COMMENT ON COLUMN public.gateway_request_logs.tool_count IS '工具数量';
COMMENT ON COLUMN public.gateway_request_logs.image_count IS '图片内容数量';
COMMENT ON COLUMN public.auth_event_logs.category IS '事件分类：login/logout/access/error';
COMMENT ON COLUMN public.auth_event_logs.event_type IS '事件类型标识';
COMMENT ON COLUMN public.auth_event_logs.success IS '事件是否成功';
COMMENT ON COLUMN public.auth_event_logs.auth_scope IS '认证范围：user/admin';
COMMENT ON COLUMN public.auth_event_logs.actor_user_id IS '关联用户 ID';
COMMENT ON COLUMN public.auth_event_logs.actor_username IS '关联用户名';
COMMENT ON COLUMN public.auth_event_logs.actor_display_name IS '关联显示名';
COMMENT ON COLUMN public.auth_event_logs.actor_role IS '关联角色';
COMMENT ON COLUMN public.auth_event_logs.provider IS '认证来源，例如 linuxdo';
COMMENT ON COLUMN public.auth_event_logs.target_path IS '目标路径';
COMMENT ON COLUMN public.auth_event_logs.ip_address IS '客户端 IP';
COMMENT ON COLUMN public.auth_event_logs.user_agent IS '客户端 User-Agent';
COMMENT ON COLUMN public.auth_event_logs.message IS '事件说明';
COMMENT ON COLUMN public.auth_event_logs.metadata IS '扩展事件详情 JSON';
COMMENT ON COLUMN public.statistics_overview.snapshot_key IS '总览快照键，默认 main';
COMMENT ON COLUMN public.statistics_overview.total_usage IS '累计总用量';
COMMENT ON COLUMN public.statistics_overview.rpm IS '当前每分钟请求数';
COMMENT ON COLUMN public.statistics_overview.tpm IS '当前每分钟 token 数';
COMMENT ON COLUMN public.statistics_request_trends.bucket_at IS '小时桶时间';
COMMENT ON COLUMN public.statistics_request_trends.success_count IS '成功请求计数';
COMMENT ON COLUMN public.statistics_request_trends.failed_count IS '失败请求计数';
COMMENT ON COLUMN public.statistics_brand_usage.brand IS '模型品牌';
COMMENT ON COLUMN public.statistics_brand_usage.usage_count IS '品牌累计用量';
COMMENT ON COLUMN public.statistics_brand_usage.sort_order IS '显示顺序';
COMMENT ON COLUMN public.statistics_daily_usage.bucket_date IS '日期桶';
COMMENT ON COLUMN public.statistics_daily_usage.usage_total IS '当日总用量';
COMMENT ON COLUMN public.statistics_hourly_usage.bucket_hour IS '小时桶';
COMMENT ON COLUMN public.statistics_hourly_usage.usage_total IS '当小时总用量';
COMMENT ON COLUMN public.statistics_model_rankings.model_name IS '模型名称';
COMMENT ON COLUMN public.statistics_model_rankings.brand IS '所属品牌';
COMMENT ON COLUMN public.statistics_model_rankings.usage_total IS '模型用量';
COMMENT ON COLUMN public.statistics_model_rankings.sort_order IS '显示顺序';
COMMENT ON COLUMN public.statistics_account_pools.pool_name IS '账号池名称';
COMMENT ON COLUMN public.statistics_account_pools.total_accounts IS '账号池总账号数';
COMMENT ON COLUMN public.statistics_account_pools.active_accounts IS '账号池活跃账号数';
COMMENT ON COLUMN public.statistics_account_pools.status_label IS '账号池状态标签';
COMMENT ON COLUMN public.statistics_account_pools.sort_order IS '显示顺序';
COMMENT ON COLUMN public.statistics_cards.card_key IS '统计卡片唯一键';
COMMENT ON COLUMN public.statistics_cards.card_type IS '卡片类型，例如 total_usage / rpm_tpm / model_rankings';
COMMENT ON COLUMN public.statistics_cards.settings IS '卡片展示设置 JSON';
COMMENT ON COLUMN public.account_pool_registry.pool_key IS '账号池唯一键';
COMMENT ON COLUMN public.account_pool_registry.table_name IS '真实数据库表名';
COMMENT ON COLUMN public.account_pool_registry.display_name IS '管理界面显示名称';
COMMENT ON COLUMN public.account_pool_registry.brand IS '默认品牌归属';
COMMENT ON COLUMN public.user_accounts.auth_source IS '账号来源：manual 或 linuxdo';
COMMENT ON COLUMN public.user_accounts.oauth_provider IS 'OAuth 提供方标识';
COMMENT ON COLUMN public.user_accounts.oauth_subject IS 'OAuth subject 唯一标识';
COMMENT ON COLUMN public.user_accounts.oauth_username IS 'OAuth 提供方返回的用户名';
COMMENT ON COLUMN public.user_accounts.avatar_url IS '用户头像地址';
COMMENT ON COLUMN public.user_accounts.profile_raw IS 'OAuth 原始用户资料 JSON';
COMMENT ON COLUMN public.user_accounts.last_login_at IS '最近登录时间';
COMMENT ON COLUMN public.user_registration_settings.settings_key IS '设置主键，默认 main';
COMMENT ON COLUMN public.user_registration_settings.registration_mode IS '注册模式：closed / open / invite_only';
COMMENT ON COLUMN public.user_registration_settings.invite_code_hint IS '邀请码注册时展示给用户的提示';
COMMENT ON COLUMN public.user_invite_codes.code IS '邀请码文本，建议大写';
COMMENT ON COLUMN public.user_invite_codes.note IS '后台备注';
COMMENT ON COLUMN public.user_invite_codes.is_enabled IS '是否可用';
COMMENT ON COLUMN public.user_invite_codes.expires_at IS '失效时间';
COMMENT ON COLUMN public.user_invite_codes.used_by_user_id IS '使用该邀请码完成注册的用户 ID';
COMMENT ON COLUMN public.user_invite_codes.used_at IS '邀请码被核销的时间';

-- -----------------------------------------------------------------------------
-- 4. 索引
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_check_history_config_id ON public.check_history (config_id);
CREATE INDEX IF NOT EXISTS idx_check_history_checked_at ON public.check_history (checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_history_config_checked ON public.check_history (config_id, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_check_configs_model_id ON public.check_configs (model_id);
CREATE INDEX IF NOT EXISTS idx_check_models_template_id ON public.check_models (template_id);
CREATE INDEX IF NOT EXISTS idx_homepage_blocks_sort_order
  ON public.homepage_blocks (sort_order ASC, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_gateway_request_logs_created_at
  ON public.gateway_request_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gateway_request_logs_profile_id
  ON public.gateway_request_logs (profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gateway_request_logs_api_key
  ON public.gateway_request_logs (gateway_api_key_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gateway_request_logs_brand
  ON public.gateway_request_logs (brand, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_event_logs_created_at
  ON public.auth_event_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_event_logs_scope_category
  ON public.auth_event_logs (auth_scope, category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gateway_api_keys_enabled
  ON public.gateway_api_keys (is_enabled, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gateway_api_keys_owner_user_id
  ON public.gateway_api_keys (owner_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_statistics_request_trends_bucket_at
  ON public.statistics_request_trends (bucket_at ASC);
CREATE INDEX IF NOT EXISTS idx_statistics_daily_usage_bucket_date
  ON public.statistics_daily_usage (bucket_date ASC);
CREATE INDEX IF NOT EXISTS idx_statistics_hourly_usage_bucket_hour
  ON public.statistics_hourly_usage (bucket_hour ASC);
CREATE INDEX IF NOT EXISTS idx_statistics_model_rankings_sort_order
  ON public.statistics_model_rankings (sort_order ASC, usage_total DESC);
CREATE INDEX IF NOT EXISTS idx_statistics_account_pools_sort_order
  ON public.statistics_account_pools (sort_order ASC);
CREATE INDEX IF NOT EXISTS idx_statistics_cards_sort_order
  ON public.statistics_cards (sort_order ASC);
CREATE INDEX IF NOT EXISTS idx_account_pool_registry_enabled
  ON public.account_pool_registry (is_enabled, table_name);
CREATE INDEX IF NOT EXISTS idx_user_accounts_oauth_subject
  ON public.user_accounts (oauth_subject)
  WHERE oauth_subject IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_accounts_oauth_provider_subject
  ON public.user_accounts (oauth_provider, oauth_subject)
  WHERE oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id
  ON public.user_sessions (user_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_invite_codes_code
  ON public.user_invite_codes (code);
CREATE INDEX IF NOT EXISTS idx_user_invite_codes_enabled
  ON public.user_invite_codes (is_enabled, created_at DESC);

-- -----------------------------------------------------------------------------
-- 5. 函数
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_check_model_template_type()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  template_type public.provider_type;
BEGIN
  IF NEW.template_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT type INTO template_type
  FROM public.check_request_templates
  WHERE id = NEW.template_id;

  IF template_type IS NULL THEN
    RETURN NEW;
  END IF;

  IF template_type <> NEW.type THEN
    RAISE EXCEPTION '模板类型不匹配: model.type=%, template.type=%', NEW.type, template_type;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_check_config_model_type()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  linked_model_type public.provider_type;
BEGIN
  SELECT type INTO linked_model_type
  FROM public.check_models
  WHERE id = NEW.model_id;

  IF linked_model_type IS NULL THEN
    RETURN NEW;
  END IF;

  IF linked_model_type <> NEW.type THEN
    RAISE EXCEPTION '模型类型不匹配: config.type=%, model.type=%', NEW.type, linked_model_type;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_recent_check_history(
  limit_per_config integer DEFAULT 60,
  target_config_ids uuid[] DEFAULT NULL
)
RETURNS TABLE (
  config_id uuid,
  status text,
  latency_ms integer,
  ping_latency_ms integer,
  checked_at timestamptz,
  message text,
  name text,
  type text,
  model text,
  endpoint text,
  group_name text
)
LANGUAGE sql
STABLE
AS $$
  WITH ranked AS (
    SELECT
      h.id AS history_id,
      h.config_id,
      h.status,
      h.latency_ms,
      h.ping_latency_ms,
      h.checked_at,
      h.message,
      row_number() OVER (PARTITION BY h.config_id ORDER BY h.checked_at DESC) AS rn
    FROM public.check_history h
    WHERE target_config_ids IS NULL OR h.config_id = ANY(target_config_ids)
  )
  SELECT
    r.config_id,
    r.status,
    r.latency_ms,
    r.ping_latency_ms::integer,
    r.checked_at,
    r.message,
    c.name,
    c.type::text,
    m.model,
    c.endpoint,
    c.group_name
  FROM ranked r
  JOIN public.check_configs c ON c.id = r.config_id
  JOIN public.check_models m ON m.id = c.model_id
  WHERE r.rn <= limit_per_config
  ORDER BY c.name ASC, r.checked_at DESC;
$$;

DROP FUNCTION IF EXISTS public.prune_check_history(integer);

CREATE OR REPLACE FUNCTION public.prune_check_history(
  retention_days integer DEFAULT NULL,
  limit_per_config integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  effective_days integer;
  deleted_count integer;
BEGIN
  effective_days := LEAST(365, GREATEST(7, COALESCE(retention_days, limit_per_config, 30)));

  DELETE FROM public.check_history
  WHERE checked_at < NOW() - (effective_days || ' days')::interval;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

COMMENT ON FUNCTION public.prune_check_history IS '清理超过指定天数的历史记录，默认保留 30 天';

CREATE OR REPLACE FUNCTION public.list_pool_tables(pattern text DEFAULT '%-pool')
RETURNS TABLE (table_name text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, information_schema
AS $$
  SELECT t.table_name::text
  FROM information_schema.tables t
  WHERE t.table_schema = 'public'
    AND t.table_type = 'BASE TABLE'
    AND t.table_name LIKE COALESCE(NULLIF(pattern, ''), '%-pool')
  ORDER BY t.table_name ASC;
$$;

COMMENT ON FUNCTION public.list_pool_tables IS '列出 public schema 中匹配 {name}-pool 命名模式的账号池数据表';

REVOKE EXECUTE ON FUNCTION public.list_pool_tables(text) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.list_pool_tables(text) TO service_role;

CREATE OR REPLACE VIEW public.gateway_api_key_usage AS
SELECT
  k.id AS gateway_api_key_id,
  COUNT(l.id)::bigint AS request_count,
  COUNT(l.id) FILTER (WHERE l.success IS TRUE)::bigint AS success_count,
  COUNT(l.id) FILTER (WHERE l.success IS FALSE)::bigint AS failed_count,
  COALESCE(SUM(COALESCE(l.total_tokens, 0)), 0)::bigint AS total_tokens,
  COALESCE(SUM(COALESCE(l.input_tokens, 0)), 0)::bigint AS input_tokens,
  COALESCE(SUM(COALESCE(l.output_tokens, 0)), 0)::bigint AS output_tokens,
  MAX(l.created_at) AS last_used_at,
  COUNT(l.id) FILTER (WHERE l.created_at >= NOW() - INTERVAL '1 minute')::bigint AS rpm_count,
  COALESCE(SUM(COALESCE(NULLIF(l.total_tokens, 0), COALESCE(l.input_tokens, 0) + COALESCE(l.output_tokens, 0), 0)) FILTER (WHERE l.created_at >= NOW() - INTERVAL '1 minute'), 0)::bigint AS tpm_count
FROM public.gateway_api_keys k
LEFT JOIN public.gateway_request_logs l
  ON l.gateway_api_key_id = k.id
GROUP BY k.id;

COMMENT ON VIEW public.gateway_api_key_usage IS '按网关访问密钥聚合的请求用量统计视图';

CREATE OR REPLACE VIEW public.gateway_user_usage_summary AS
SELECT
  l.user_id,
  COUNT(l.id)::bigint AS request_count,
  COUNT(l.id) FILTER (WHERE l.success IS TRUE)::bigint AS success_count,
  COUNT(l.id) FILTER (WHERE l.success IS FALSE)::bigint AS failed_count,
  COALESCE(SUM(COALESCE(l.total_tokens, 0)), 0)::bigint AS total_tokens,
  COALESCE(SUM(COALESCE(l.input_tokens, 0)), 0)::bigint AS input_tokens,
  COALESCE(SUM(COALESCE(l.output_tokens, 0)), 0)::bigint AS output_tokens,
  MAX(l.created_at) AS last_request_at,
  COUNT(l.id) FILTER (WHERE l.created_at >= NOW() - INTERVAL '1 minute')::bigint AS rpm_count,
  COALESCE(SUM(COALESCE(NULLIF(l.total_tokens, 0), COALESCE(l.input_tokens, 0) + COALESCE(l.output_tokens, 0), 0)) FILTER (WHERE l.created_at >= NOW() - INTERVAL '1 minute'), 0)::bigint AS tpm_count
FROM public.gateway_request_logs l
WHERE l.user_id IS NOT NULL
GROUP BY l.user_id;

COMMENT ON VIEW public.gateway_user_usage_summary IS '按用户聚合的网关请求、token、RPM、TPM 统计视图';

CREATE OR REPLACE VIEW public.gateway_user_model_usage AS
SELECT
  l.user_id,
  COALESCE(NULLIF(BTRIM(l.mapped_model), ''), NULLIF(BTRIM(l.external_model), ''), 'unknown') AS model_name,
  COALESCE(NULLIF(BTRIM(l.brand), ''), 'other') AS brand,
  COUNT(l.id)::bigint AS request_count,
  COALESCE(SUM(COALESCE(l.total_tokens, 0)), 0)::bigint AS total_tokens,
  MAX(l.created_at) AS last_used_at
FROM public.gateway_request_logs l
WHERE l.user_id IS NOT NULL
GROUP BY
  l.user_id,
  COALESCE(NULLIF(BTRIM(l.mapped_model), ''), NULLIF(BTRIM(l.external_model), ''), 'unknown'),
  COALESCE(NULLIF(BTRIM(l.brand), ''), 'other');

COMMENT ON VIEW public.gateway_user_model_usage IS '按用户和模型聚合的用量统计视图';

-- -----------------------------------------------------------------------------
-- 6. 触发器
-- -----------------------------------------------------------------------------

DROP TRIGGER IF EXISTS update_check_configs_updated_at ON public.check_configs;
CREATE TRIGGER update_check_configs_updated_at
  BEFORE UPDATE ON public.check_configs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS validate_check_models_template_type ON public.check_models;
CREATE TRIGGER validate_check_models_template_type
  BEFORE INSERT OR UPDATE OF template_id, type ON public.check_models
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_check_model_template_type();

DROP TRIGGER IF EXISTS validate_check_configs_model_type ON public.check_configs;
CREATE TRIGGER validate_check_configs_model_type
  BEFORE INSERT OR UPDATE OF model_id, type ON public.check_configs
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_check_config_model_type();

DROP TRIGGER IF EXISTS update_check_models_updated_at ON public.check_models;
CREATE TRIGGER update_check_models_updated_at
  BEFORE UPDATE ON public.check_models
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_check_request_templates_updated_at ON public.check_request_templates;
CREATE TRIGGER update_check_request_templates_updated_at
  BEFORE UPDATE ON public.check_request_templates
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_group_info_updated_at ON public.group_info;
CREATE TRIGGER update_group_info_updated_at
  BEFORE UPDATE ON public.group_info
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_homepage_blocks_updated_at ON public.homepage_blocks;
CREATE TRIGGER update_homepage_blocks_updated_at
  BEFORE UPDATE ON public.homepage_blocks
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_homepage_content_updated_at ON public.homepage_content;
CREATE TRIGGER update_homepage_content_updated_at
  BEFORE UPDATE ON public.homepage_content
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_gateway_profiles_updated_at ON public.gateway_profiles;
CREATE TRIGGER update_gateway_profiles_updated_at
  BEFORE UPDATE ON public.gateway_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_gateway_api_keys_updated_at ON public.gateway_api_keys;
CREATE TRIGGER update_gateway_api_keys_updated_at
  BEFORE UPDATE ON public.gateway_api_keys
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_statistics_overview_updated_at ON public.statistics_overview;
CREATE TRIGGER update_statistics_overview_updated_at
  BEFORE UPDATE ON public.statistics_overview
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_statistics_brand_usage_updated_at ON public.statistics_brand_usage;
CREATE TRIGGER update_statistics_brand_usage_updated_at
  BEFORE UPDATE ON public.statistics_brand_usage
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_statistics_model_rankings_updated_at ON public.statistics_model_rankings;
CREATE TRIGGER update_statistics_model_rankings_updated_at
  BEFORE UPDATE ON public.statistics_model_rankings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_statistics_account_pools_updated_at ON public.statistics_account_pools;
CREATE TRIGGER update_statistics_account_pools_updated_at
  BEFORE UPDATE ON public.statistics_account_pools
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_statistics_cards_updated_at ON public.statistics_cards;
CREATE TRIGGER update_statistics_cards_updated_at
  BEFORE UPDATE ON public.statistics_cards
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_account_pool_registry_updated_at ON public.account_pool_registry;
CREATE TRIGGER update_account_pool_registry_updated_at
  BEFORE UPDATE ON public.account_pool_registry
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_accounts_updated_at ON public.user_accounts;
CREATE TRIGGER update_user_accounts_updated_at
  BEFORE UPDATE ON public.user_accounts
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_registration_settings_updated_at ON public.user_registration_settings;
CREATE TRIGGER update_user_registration_settings_updated_at
  BEFORE UPDATE ON public.user_registration_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_invite_codes_updated_at ON public.user_invite_codes;
CREATE TRIGGER update_user_invite_codes_updated_at
  BEFORE UPDATE ON public.user_invite_codes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 7. 视图
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.availability_stats AS
SELECT
  config_id,
  '7d'::text AS period,
  COUNT(*) AS total_checks,
  COUNT(*) FILTER (WHERE status IN ('operational', 'degraded')) AS operational_count,
  ROUND(
    100.0 * COUNT(*) FILTER (WHERE status IN ('operational', 'degraded')) / NULLIF(COUNT(*), 0),
    2
  ) AS availability_pct
FROM public.check_history
WHERE checked_at > NOW() - INTERVAL '7 days'
GROUP BY config_id

UNION ALL

SELECT
  config_id,
  '15d'::text AS period,
  COUNT(*) AS total_checks,
  COUNT(*) FILTER (WHERE status IN ('operational', 'degraded')) AS operational_count,
  ROUND(
    100.0 * COUNT(*) FILTER (WHERE status IN ('operational', 'degraded')) / NULLIF(COUNT(*), 0),
    2
  ) AS availability_pct
FROM public.check_history
WHERE checked_at > NOW() - INTERVAL '15 days'
GROUP BY config_id

UNION ALL

SELECT
  config_id,
  '30d'::text AS period,
  COUNT(*) AS total_checks,
  COUNT(*) FILTER (WHERE status IN ('operational', 'degraded')) AS operational_count,
  ROUND(
    100.0 * COUNT(*) FILTER (WHERE status IN ('operational', 'degraded')) / NULLIF(COUNT(*), 0),
    2
  ) AS availability_pct
FROM public.check_history
WHERE checked_at > NOW() - INTERVAL '30 days'
GROUP BY config_id;

COMMENT ON VIEW public.availability_stats IS '可用性统计视图，提供 7天/15天/30天 的可用性百分比';

-- -----------------------------------------------------------------------------
-- 8. RLS
-- -----------------------------------------------------------------------------

ALTER TABLE public.check_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_request_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.homepage_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.homepage_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_poller_leases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gateway_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gateway_api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gateway_request_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auth_event_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_overview ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_request_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_brand_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_daily_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_hourly_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_model_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_account_pools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistics_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_pool_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_registration_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_invite_codes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'check_history' AND policyname = 'allow_anon_select_history'
  ) THEN
    CREATE POLICY allow_anon_select_history
      ON public.check_history
      FOR SELECT
      TO anon
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'group_info' AND policyname = 'allow_public_read_group_info'
  ) THEN
    CREATE POLICY allow_public_read_group_info
      ON public.group_info
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'system_notifications' AND policyname = 'allow_public_read_notifications'
  ) THEN
    CREATE POLICY allow_public_read_notifications
      ON public.system_notifications
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'homepage_blocks' AND policyname = 'allow_public_read_homepage_blocks'
  ) THEN
    CREATE POLICY allow_public_read_homepage_blocks
      ON public.homepage_blocks
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'homepage_content' AND policyname = 'allow_public_read_homepage_content'
  ) THEN
    CREATE POLICY allow_public_read_homepage_content
      ON public.homepage_content
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DROP POLICY IF EXISTS allow_public_read_gateway_profiles ON public.gateway_profiles;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_overview' AND policyname = 'allow_public_read_statistics_overview'
  ) THEN
    CREATE POLICY allow_public_read_statistics_overview
      ON public.statistics_overview
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_request_trends' AND policyname = 'allow_public_read_statistics_request_trends'
  ) THEN
    CREATE POLICY allow_public_read_statistics_request_trends
      ON public.statistics_request_trends
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_brand_usage' AND policyname = 'allow_public_read_statistics_brand_usage'
  ) THEN
    CREATE POLICY allow_public_read_statistics_brand_usage
      ON public.statistics_brand_usage
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_daily_usage' AND policyname = 'allow_public_read_statistics_daily_usage'
  ) THEN
    CREATE POLICY allow_public_read_statistics_daily_usage
      ON public.statistics_daily_usage
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_hourly_usage' AND policyname = 'allow_public_read_statistics_hourly_usage'
  ) THEN
    CREATE POLICY allow_public_read_statistics_hourly_usage
      ON public.statistics_hourly_usage
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_model_rankings' AND policyname = 'allow_public_read_statistics_model_rankings'
  ) THEN
    CREATE POLICY allow_public_read_statistics_model_rankings
      ON public.statistics_model_rankings
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_account_pools' AND policyname = 'allow_public_read_statistics_account_pools'
  ) THEN
    CREATE POLICY allow_public_read_statistics_account_pools
      ON public.statistics_account_pools
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'statistics_cards' AND policyname = 'allow_public_read_statistics_cards'
  ) THEN
    CREATE POLICY allow_public_read_statistics_cards
      ON public.statistics_cards
      FOR SELECT
      TO public
      USING (true);
  END IF;
END;
$$;

DROP POLICY IF EXISTS allow_public_read_account_pool_registry ON public.account_pool_registry;
DROP POLICY IF EXISTS allow_public_read_user_registration_settings ON public.user_registration_settings;
DROP POLICY IF EXISTS allow_public_read_user_invite_codes ON public.user_invite_codes;

-- -----------------------------------------------------------------------------
-- 9. 初始化数据
-- -----------------------------------------------------------------------------

INSERT INTO public.check_poller_leases (lease_key, leader_id, lease_expires_at)
VALUES ('poller', NULL, to_timestamp(0))
ON CONFLICT (lease_key) DO NOTHING;

INSERT INTO public.homepage_blocks (
  slug,
  title,
  href,
  description,
  status_label,
  image_data_url,
  col_span,
  row_span,
  sort_order,
  is_active
)
VALUES
  ('check', 'Check', '/check', '打开实时检测服务面板。', 'Live', NULL, 2, 1, 0, true),
  ('admin', 'Admin', '/admin', '进入管理主页，维护方块与内容。', 'Control', NULL, 2, 1, 1, true),
  ('github-org', 'GitHub Org', 'https://github.com/A-GW-N', '组织仓库与公开项目入口。', 'Link', NULL, 1, 1, 2, true),
  ('gateway-03', 'Gateway 03', '#', '预留业务入口，后续接真实模块。', 'Reserved', NULL, 1, 1, 3, true),
  ('gateway-04', 'Gateway 04', '#', '预留业务入口，后续接真实模块。', 'Reserved', NULL, 1, 1, 4, true),
  ('gateway-05', 'Gateway 05', '#', '预留业务入口，后续接真实模块。', 'Reserved', NULL, 1, 1, 5, true),
  ('gateway-06', 'Gateway 06', '#', '预留业务入口，后续接真实模块。', 'Reserved', NULL, 1, 1, 6, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.gateway_profiles (
  profile_key,
  display_name,
  provider_slug,
  endpoint_url,
  auth_mode,
  request_mode,
  model_mappings,
  brand_mappings,
  default_headers,
  extra_payload,
  pool_table_pattern,
  is_enabled
)
VALUES (
  'main-proxy',
  'Main Proxy',
  'openai-compatible',
  'https://api.openai.com/v1/chat/completions',
  'bearer',
  'openai',
  '{"gpt-4.1":"gpt-4.1","gpt-4o":"gpt-4o","gemini-2.5-pro":"gemini-2.5-pro","claude-3.7-sonnet":"claude-3.7-sonnet"}'::jsonb,
  '{"gpt-4.1":"gpt","gpt-4o":"gpt","gemini-2.5-pro":"gemini","claude-3.7-sonnet":"claude"}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '%-pool',
  false
)
ON CONFLICT (profile_key) DO NOTHING;

INSERT INTO public.statistics_overview (snapshot_key, total_usage, rpm, tpm)
VALUES ('main', 0, 0, 0)
ON CONFLICT (snapshot_key) DO NOTHING;

INSERT INTO public.statistics_brand_usage (brand, usage_count, sort_order)
VALUES
  ('gpt', 0, 0),
  ('gemini', 0, 1),
  ('claude', 0, 2),
  ('other', 0, 3)
ON CONFLICT (brand) DO NOTHING;

INSERT INTO public.statistics_cards (card_key, title, card_type, description, sort_order, is_enabled, settings)
VALUES
  ('total-usage', '总用量', 'total_usage', '累计请求与 token 使用总量', 0, true, '{}'::jsonb),
  ('rpm-tpm', 'RPM / TPM', 'rpm_tpm', '每分钟请求数与每分钟 token 数', 1, true, '{}'::jsonb),
  ('daily-usage', '7天每天用量', 'daily_usage', '最近 7 天按天聚合的用量', 2, true, '{}'::jsonb),
  ('hourly-usage', '小时用量', 'hourly_usage', '按小时聚合的请求或 token 使用量', 3, true, '{}'::jsonb),
  ('model-rankings', '模型用量排行榜', 'model_rankings', '按模型聚合的用量排行', 4, true, '{}'::jsonb),
  ('account-pools', '账号池显示', 'account_pools', '展示账号池和活跃账号情况', 5, true, '{}'::jsonb)
ON CONFLICT (card_key) DO NOTHING;

INSERT INTO public.user_registration_settings (settings_key, registration_mode, invite_code_hint)
VALUES ('main', 'closed', '')
ON CONFLICT (settings_key) DO NOTHING;
